[settings]
experimental = true

[tools]
bat = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "lts"
protoc = "latest"
python = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
zellij = "latest"
ghq = "latest"
zoxide = "latest"
jless = "latest"
java = "21"
gradle = "latest"
kotlin = "latest"
rust = "latest"
