[settings]
experimental = true

[tools]
bat = "latest"
fd = "latest"
fzf = "latest"
golang = "latest"
neovim = "latest"
nodejs = "20"
protoc = "latest"
python = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
xh = "latest"
