[tools]
python = 'latest'
golang = 'latest'
nodejs = '18'
starship = 'latest'
bat = 'latest'
fd = 'latest'
fzf = 'latest'
ripgrep = 'latest'
gitui = 'latest'
jq = 'latest'
stylua = 'latest'
xh = 'latest'
neovim = 'latest'
